# ============================================================================
# local-config.nix - User Feature Selection
# ============================================================================
# Auto-generated by rebuild.sh. You can also edit by hand.
# After changing, run:  sudo nixos-rebuild switch --flake .#<host>
#
# true = installed,  false = not installed
# ============================================================================
{ ... }:

{
  # -- Dev toolchains -------------------------------------------------------
  my.dev.nodejs.enable  = false;
  my.dev.python.enable  = false;
  my.dev.rust.enable    = false;
  my.dev.go.enable      = false;
  my.dev.devops.enable  = false;

  # -- Editors --------------------------------------------------------------
  my.editors.neovim.enable = false;
  my.editors.helix.enable  = false;
  my.editors.vscode.enable = false;

  # -- GUI apps (ignored on WSL) --------------------------------------------
  my.gui.browsers.enable  = false;
  my.gui.media.enable     = false;
  my.gui.alacritty.enable = false;
}
