#!/usr/bin/env bash
# ============================================================================
# rebuild.sh - Interactive NixOS/nix-darwin rebuild
# ============================================================================
# RULES:
#   Y = Yes, install/enable this tool
#   N = No, skip (if already installed, it STAYS installed -- never removed)
#
# To REMOVE a tool: ./rebuild.sh --remove <tool> <host>
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/local-config.nix"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ---- All tools and their config keys --------------------------------------
TOOLS=(
  "nodejs:my.dev.nodejs.enable:Node.js (npm, pnpm, Bun, Deno, TypeScript)"
  "python:my.dev.python.enable:Python (Poetry, Black, Ruff, mypy)"
  "rust:my.dev.rust.enable:Rust (Cargo, clippy, rust-analyzer)"
  "go:my.dev.go.enable:Go (gopls, golangci-lint, delve)"
  "devops:my.dev.devops.enable:DevOps (Terraform, Ansible, K8s, Docker)"
  "neovim:my.editors.neovim.enable:Neovim (with LSP config)"
  "helix:my.editors.helix.enable:Helix editor"
  "vscode:my.editors.vscode.enable:VS Code (with extensions)"
  "browsers:my.gui.browsers.enable:Browsers (Firefox + Chromium)"
  "media:my.gui.media.enable:Media (Spotify, VLC, OBS, Discord)"
  "alacritty:my.gui.alacritty.enable:Alacritty terminal (optional)"
)

# ---- Read existing config into associative array --------------------------
declare -A CURRENT

read_existing_config() {
  # Default everything to false
  for entry in "${TOOLS[@]}"; do
    IFS=':' read -r name key _ <<< "$entry"
    CURRENT["$name"]="false"
  done

  if [[ -f "$CONFIG_FILE" ]]; then
    for entry in "${TOOLS[@]}"; do
      IFS=':' read -r name key _ <<< "$entry"
      val=$(grep "$key" "$CONFIG_FILE" 2>/dev/null | grep -oE '(true|false)' | head -1)
      CURRENT["$name"]="${val:-false}"
    done
  fi
}

# ---- Host selection -------------------------------------------------------
select_host() {
  echo ""
  echo -e "${YELLOW}${BOLD}Select your host:${NC}"
  echo -e "  1) pc       - Main PC (x86_64 NixOS, Cinnamon desktop)"
  echo -e "  2) vmware   - VMware VM (x86_64 NixOS, Cinnamon desktop)"
  echo -e "  3) wsl      - Windows Subsystem for Linux (headless)"
  echo -e "  4) macbook  - macOS via nix-darwin (aarch64)"
  echo ""

  while true; do
    echo -ne "  Enter choice [1-4]: "
    read -r choice
    case "$choice" in
      1) HOST="pc";      IS_DARWIN=false; IS_WSL=false; break ;;
      2) HOST="vmware";  IS_DARWIN=false; IS_WSL=false; break ;;
      3) HOST="wsl";     IS_DARWIN=false; IS_WSL=true;  break ;;
      4) HOST="macbook"; IS_DARWIN=true;  IS_WSL=false;  break ;;
      *) echo -e "  ${RED}Invalid. Pick 1-4.${NC}" ;;
    esac
  done
  echo -e "  ${GREEN}Host: $HOST${NC}"
  echo ""
}

# ---- Simple Y/N prompt ----------------------------------------------------
# Y = yes, install this tool (set to true)
# N = no, I don't need this tool (set to false)
ask_yn() {
  local name="$1"
  local label="$2"

  echo -ne "  ${BOLD}$label${NC} (y/n): "
  read -r answer

  case "$answer" in
    [Yy]|[Yy]es)
      CURRENT["$name"]="true"
      ;;
    [Nn]|[Nn]o)
      CURRENT["$name"]="false"
      ;;
    *)
      # Empty or invalid = keep current state
      ;;
  esac
}

# ---- Feature selection ----------------------------------------------------
select_features() {
  echo -e "${YELLOW}${BOLD}Dev toolchains:${NC}"
  echo -e "${DIM}  Y = install, N = skip (already installed tools are NEVER removed)${NC}"
  echo ""

  ask_yn "nodejs"  "Node.js (npm, pnpm, Bun, Deno, TypeScript)"
  ask_yn "python"  "Python (Poetry, Black, Ruff, mypy)"
  ask_yn "rust"    "Rust (Cargo, clippy, rust-analyzer)"
  ask_yn "go"      "Go (gopls, golangci-lint, delve)"
  ask_yn "devops"  "DevOps (Terraform, Ansible, K8s, Docker)"

  echo ""
  echo -e "${YELLOW}${BOLD}Editors:${NC}"
  echo ""

  ask_yn "neovim"  "Neovim (with LSP config)"
  ask_yn "helix"   "Helix editor"
  ask_yn "vscode"  "VS Code (with extensions)"

  # GUI only for desktop hosts
  if [[ "$IS_WSL" == "false" ]]; then
    echo ""
    echo -e "${YELLOW}${BOLD}GUI apps:${NC}"
    echo ""

    ask_yn "browsers"  "Browsers (Firefox + Chromium)"
    ask_yn "media"     "Media (Spotify, VLC, OBS, Discord)"
    ask_yn "alacritty" "Alacritty terminal (optional, NixOS has its own)"
  fi
}

# ---- Write local-config.nix from CURRENT array ---------------------------
write_config() {
  cat > "$CONFIG_FILE" << EOF
# ============================================================================
# local-config.nix - User Feature Selection (auto-generated by rebuild.sh)
# ============================================================================
# Y = installed, N = skipped (never removed).
# To remove a tool: ./rebuild.sh --remove <tool> <host>
# ============================================================================
{ ... }:

{
  # -- Dev toolchains -------------------------------------------------------
  my.dev.nodejs.enable  = ${CURRENT[nodejs]};
  my.dev.python.enable  = ${CURRENT[python]};
  my.dev.rust.enable    = ${CURRENT[rust]};
  my.dev.go.enable      = ${CURRENT[go]};
  my.dev.devops.enable  = ${CURRENT[devops]};

  # -- Editors --------------------------------------------------------------
  my.editors.neovim.enable = ${CURRENT[neovim]};
  my.editors.helix.enable  = ${CURRENT[helix]};
  my.editors.vscode.enable = ${CURRENT[vscode]};

  # -- GUI apps (ignored on WSL) --------------------------------------------
  my.gui.browsers.enable  = ${CURRENT[browsers]};
  my.gui.media.enable     = ${CURRENT[media]};
  my.gui.alacritty.enable = ${CURRENT[alacritty]};
}
EOF

  echo ""
  echo -e "${GREEN}Saved config.${NC}"
}

# ---- Show summary ---------------------------------------------------------
show_summary() {
  echo ""
  echo -e "${CYAN}${BOLD}Summary for $HOST:${NC}"
  echo ""
  for entry in "${TOOLS[@]}"; do
    IFS=':' read -r name key label <<< "$entry"
    if [[ "${CURRENT[$name]}" == "true" ]]; then
      echo -e "  ${GREEN}+ $label${NC}"
    else
      echo -e "  ${DIM}- $label${NC}"
    fi
  done
  echo ""
}

# ---- Quick --add / --remove -----------------------------------------------
quick_toggle() {
  local action="$1"  # "add" or "remove"
  local tool="$2"

  # Normalize aliases
  case "$tool" in
    node)  tool="nodejs" ;;
    nvim)  tool="neovim" ;;
    hx)    tool="helix"  ;;
    code)  tool="vscode" ;;
  esac

  # Check tool exists
  local found=false
  for entry in "${TOOLS[@]}"; do
    IFS=':' read -r name _ _ <<< "$entry"
    [[ "$name" == "$tool" ]] && found=true && break
  done

  if [[ "$found" == "false" ]]; then
    echo -e "${RED}Unknown tool: $tool${NC}"
    echo "Available: nodejs python rust go devops neovim helix vscode browsers media alacritty"
    exit 1
  fi

  if [[ "$action" == "add" ]]; then
    CURRENT["$tool"]="true"
    echo -e "${GREEN}Enabling: $tool${NC}"
  else
    CURRENT["$tool"]="false"
    echo -e "${YELLOW}Removing: $tool${NC}"
  fi
}

# ---- Rebuild --------------------------------------------------------------
LOG_FILE="$SCRIPT_DIR/rebuild.log"

do_rebuild() {
  echo ""
  local cmd
  if [[ "$IS_DARWIN" == "true" ]]; then
    cmd="darwin-rebuild switch --flake .#$HOST"
  else
    cmd="sudo nixos-rebuild switch --flake .#$HOST"
  fi

  echo -e "${BOLD}Running: $cmd${NC}"
  echo -e "${DIM}(log saved to: $LOG_FILE)${NC}"
  echo ""

  # Run rebuild and capture output to both terminal AND log file
  if $cmd 2>&1 | tee "$LOG_FILE"; then
    echo ""
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}${BOLD}  Rebuild SUCCESSFUL!${NC}"
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}Open a new terminal to use your tools.${NC}"
  else
    echo ""
    echo -e "${RED}${BOLD}============================================${NC}"
    echo -e "${RED}${BOLD}  Rebuild FAILED! Check log: $LOG_FILE${NC}"
    echo -e "${RED}${BOLD}============================================${NC}"
  fi

  echo ""
  echo -e "${YELLOW}Press Enter to close...${NC}"
  read -r
}

# ============================================================================
# Main
# ============================================================================
main() {
  echo ""
  echo -e "${CYAN}${BOLD}============================================${NC}"
  echo -e "${CYAN}${BOLD}  NixOS Config Rebuild - nayandas69${NC}"
  echo -e "${CYAN}${BOLD}============================================${NC}"

  # ALWAYS read existing config first so nothing gets lost
  read_existing_config

  # --quick: rebuild without asking
  if [[ "${1:-}" == "--quick" ]]; then
    HOST="${2:-vmware}"
    IS_DARWIN=false; IS_WSL=false
    [[ "$HOST" == "macbook" ]] && IS_DARWIN=true
    [[ "$HOST" == "wsl" ]] && IS_WSL=true
    echo -e "${YELLOW}Quick rebuild for: $HOST (keeping all current tools)${NC}"
    do_rebuild
    exit 0
  fi

  # --add or --remove: toggle one tool without full menu
  if [[ "${1:-}" == "--add" || "${1:-}" == "--remove" ]]; then
    local action="${1#--}"
    local tool="${2:?Usage: ./rebuild.sh --$action <tool> [host]}"
    HOST="${3:-vmware}"
    IS_DARWIN=false; IS_WSL=false
    [[ "$HOST" == "macbook" ]] && IS_DARWIN=true
    [[ "$HOST" == "wsl" ]] && IS_WSL=true

    quick_toggle "$action" "$tool"
    write_config
    git -C "$SCRIPT_DIR" add "$CONFIG_FILE" 2>/dev/null || true
    do_rebuild
    exit 0
  fi

  # Interactive mode
  select_host
  select_features
  write_config
  show_summary

  echo -ne "  ${BOLD}Proceed with rebuild?${NC} (y/n): "
  read -r answer
  case "$answer" in
    [Yy]|[Yy]es|"")
      git -C "$SCRIPT_DIR" add "$CONFIG_FILE" 2>/dev/null || true
      do_rebuild
      ;;
    *)
      echo -e "${YELLOW}Cancelled. Config saved -- run again when ready.${NC}"
      ;;
  esac
}

main "$@"
