# ============================================================================
# hosts/pc/default.nix - Main PC Configuration
# ============================================================================
# This licks the main desktop into shape. Cinnamon desktop with every dev
# tool a full-stack developer could want. This is the primary workstation
# config for nayandas running NixOS 25.11 on x86_64.
#
# Rebuild with:
#   sudo nixos-rebuild switch --flake .#pc
# ============================================================================
{ config, pkgs, lib, user, ... }:

{
  imports = [
    # Hardware-specific config generated by nixos-generate-config
    ./hardware-configuration.nix

    # Shared NixOS modules - licks in all the system-level goodies
    ../../modules/core.nix
    ../../modules/desktop/cinnamon.nix
    ../../modules/networking.nix
    ../../modules/virtualization.nix
    ../../modules/services.nix
  ];

  # -- Hostname -------------------------------------------------------------
  networking.hostName = "nayandas";

  # -- Bootloader -----------------------------------------------------------
  # systemd-boot for UEFI systems - licks the boot process nice and clean
  boot.loader = {
    systemd-boot.enable = true;
    systemd-boot.configurationLimit = 10; # keep last 10 generations
    efi.canTouchEfiVariables = true;
  };

  # -- User account ---------------------------------------------------------
  # The main user account. Password is set via `passwd` after first boot.
  users.users.${user} = {
    isNormalUser = true;
    description = "Nayan Das";
    extraGroups = [
      "wheel"           # sudo access
      "networkmanager"  # manage network connections
      "docker"          # docker without sudo
      "video"           # GPU / screen brightness access
      "audio"           # audio device access
    ];
    shell = pkgs.zsh;
    # TODO: Remove initialPassword after first boot and set a real one with `passwd`
    initialPassword = "changeme";
  };

  # Enable zsh system-wide so it can be used as a login shell
  programs.zsh.enable = true;

  # -- Sound ----------------------------------------------------------------
  # PipeWire licks the audio stack into modern shape (replaces PulseAudio)
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # -- Firmware / hardware --------------------------------------------------
  hardware.enableRedistributableFirmware = true;
  hardware.graphics.enable = true;

  # -- System packages (host-level) -----------------------------------------
  # These are system-wide; most dev tools live in home-manager instead
  environment.systemPackages = with pkgs; [
    vim          # fallback editor in case home-manager breaks
    git
    curl
    wget
    pciutils     # lspci
    usbutils     # lsusb
    file
    unzip
    htop
  ];

  # -- State version --------------------------------------------------------
  # DO NOT change this after initial install. It licks the system state into
  # a known baseline. Changing it can break stateful services.
  system.stateVersion = "25.11";
}
