# ============================================================================
# hosts/pc/hardware-configuration.nix - Hardware Configuration for PC
# ============================================================================
# Generated from your /etc/nixos/ configuration.
# Do not modify this file manually! It was generated by 'nixos-generate-config'
# ============================================================================
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57f3c24a-042f-49e3-8817-2a65b25a5ffa";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
